### PR TITLE
Convert to Typescript

### PR DESCRIPTION
**Pull request by andyedinborough**
This converts the project to typescript and implements a Platform to devices can be discovered automatically.

### CODE REVIEW

**Comment by andyedinborough** [comment]
I need to test the existing accessory config to make sure it's backwards compatible, but I wanted to get this submitted to get your thoughts.

**Comment by andyedinborough** [comment]
I also need to update the README.

**Comment by knuckleheadsmiff** [comment]
I can’t get to this until Friday at the earliest but I have no issue with you owning the merge of this. With all the changes made this is really more your code now (which really is 100% fine with me.) I think you have the access rights to do it.

**Comment by knuckleheadsmiff** [comment]
“??” is new syntax for me! I really have not programmed in JS for a while. I retired (early) about  7 years ago  and most of my JS was on the browser UI side and usually I had to use LCD language syntax/features.

**Comment by knuckleheadsmiff** [comment]
I looked over everything and accepted. Your changes are fantastic. Not really the old code at all, this is much better in all possible ways! 

Thanks a bunch. You should feel free to merge any and all future changes directly.

**Comment by knuckleheadsmiff** [comment]
running NPM publish the following is output:

sh: eslint: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! homebridge-garagedoor-ryobi@0.3.2 lint: `eslint src/**.ts --max-warnings=0`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the homebridge-garagedoor-ryobi@0.3.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/russ/.npm/_logs/2021-04-23T17_11_50_771Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-garagedoor-ryobi@0.3.2 prepublishOnly: `npm run lint && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-garagedoor-ryobi@0.3.2 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/russ/.npm/_logs/2021-04-23T17_11_50_810Z-debug.log




------------------------

russ@russ-air homebridge-garagedoor-ryobi %  cat /Users/russ/.npm/_logs/2021-04-23T17_11_00_283Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@6.14.8
3 info using node@v12.16.3
4 verbose npm-session 78dfe208d981ce2c
5 verbose publish [ '.' ]
6 info lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublish: homebridge-garagedoor-ryobi@0.3.2
7 info lifecycle homebridge-garagedoor-ryobi@0.3.2~prepare: homebridge-garagedoor-ryobi@0.3.2
8 info lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: homebridge-garagedoor-ryobi@0.3.2
9 verbose lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: unsafe-perm in lifecycle true
10 verbose lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/russ/Documents/GitHub/homebridge-garagedoor-ryobi/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin
11 verbose lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: CWD: .
12 silly lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: Args: [ '-c', 'npm run lint && npm run build' ]
13 silly lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: Returned: code: 1  signal: null
14 info lifecycle homebridge-garagedoor-ryobi@0.3.2~prepublishOnly: Failed to exec prepublishOnly script
15 verbose stack Error: homebridge-garagedoor-ryobi@0.3.2 prepublishOnly: `npm run lint && npm run build`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
15 verbose stack     at EventEmitter.emit (events.js:310:20)
15 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
15 verbose stack     at ChildProcess.emit (events.js:310:20)
15 verbose stack     at maybeClose (internal/child_process.js:1021:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
16 verbose pkgid homebridge-garagedoor-ryobi@0.3.2
17 verbose cwd /Users/russ/Documents/GitHub/homebridge-garagedoor-ryobi
18 verbose Darwin 20.3.0
19 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
20 verbose node v12.16.3
21 verbose npm  v6.14.8
22 error code ELIFECYCLE
23 error errno 1
24 error homebridge-garagedoor-ryobi@0.3.2 prepublishOnly: `npm run lint && npm run build`
24 error Exit status 1
25 error Failed at the homebridge-garagedoor-ryobi@0.3.2 prepublishOnly script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by knuckleheadsmiff** [comment]
_(I initially had an error becuase I did not have eslint on my fairly new Mac)_
-----------------------------------------------------------------
% npm publish                                                   

> homebridge-garagedoor-ryobi@0.3.2 prepublishOnly .
> npm run lint && npm run build


> homebridge-garagedoor-ryobi@0.3.2 lint /Users/russ/Documents/GitHub/homebridge-garagedoor-ryobi
> eslint src/**.ts --max-warnings=0


> homebridge-garagedoor-ryobi@0.3.2 build /Users/russ/Documents/GitHub/homebridge-garagedoor-ryobi
> rimraf ./dist && tsc

npm notice 
npm notice 📦  homebridge-garagedoor-ryobi@0.3.2
npm notice === Tarball Contents === 
npm notice 1.4kB  .eslintrc                        
npm notice 67B    .prettierrc                      
npm notice 448B   dist/index.js                    
npm notice 113B   dist/RyobiGDO.js                 
npm notice 9.1kB  dist/RyobiGDOAccessory.js        
npm notice 10.2kB dist/RyobiGDOApi.js              
npm notice 124B   dist/RyobiGDOCredentials.js      
npm notice 119B   dist/RyobiGDODevice.js           
npm notice 4.3kB  dist/RyobiGDOPlatform.js         
npm notice 120B   dist/RyobiGDOSession.js          
npm notice 257B   dist/settings.js                 
npm notice 867B   config.schema.json               
npm notice 1.2kB  package.json                     
npm notice 528B   tsconfig.json                    
npm notice 166B   dist/index.d.ts.map              
npm notice 300B   dist/index.js.map                
npm notice 3.4kB  dist/RyobiGDO.d.ts.map           
npm notice 108B   dist/RyobiGDO.js.map             
npm notice 1.4kB  dist/RyobiGDOAccessory.d.ts.map  
npm notice 7.6kB  dist/RyobiGDOAccessory.js.map    
npm notice 871B   dist/RyobiGDOApi.d.ts.map        
npm notice 8.6kB  dist/RyobiGDOApi.js.map          
npm notice 210B   dist/RyobiGDOCredentials.d.ts.map
npm notice 130B   dist/RyobiGDOCredentials.js.map  
npm notice 407B   dist/RyobiGDODevice.d.ts.map     
npm notice 120B   dist/RyobiGDODevice.js.map       
npm notice 630B   dist/RyobiGDOPlatform.d.ts.map   
npm notice 2.4kB  dist/RyobiGDOPlatform.js.map     
npm notice 282B   dist/RyobiGDOSession.d.ts.map    
npm notice 122B   dist/RyobiGDOSession.js.map      
npm notice 172B   dist/settings.d.ts.map           
npm notice 173B   dist/settings.js.map             
npm notice 7.6kB  README.md                        
npm notice 139B   dist/index.d.ts                  
npm notice 387B   src/index.ts                     
npm notice 278B   tests/integration.ts             
npm notice 2.8kB  dist/RyobiGDO.d.ts               
npm notice 2.6kB  src/RyobiGDO.ts                  
npm notice 1.6kB  dist/RyobiGDOAccessory.d.ts      
npm notice 8.4kB  src/RyobiGDOAccessory.ts         
npm notice 968B   dist/RyobiGDOApi.d.ts            
npm notice 7.8kB  src/RyobiGDOApi.ts               
npm notice 131B   dist/RyobiGDOCredentials.d.ts    
npm notice 78B    src/RyobiGDOCredentials.ts       
npm notice 271B   dist/RyobiGDODevice.d.ts         
npm notice 209B   src/RyobiGDODevice.ts            
npm notice 715B   dist/RyobiGDOPlatform.d.ts       
npm notice 3.9kB  src/RyobiGDOPlatform.ts          
npm notice 190B   dist/RyobiGDOSession.d.ts        
npm notice 139B   src/RyobiGDOSession.ts           
npm notice 154B   dist/settings.d.ts               
npm notice 100B   src/settings.ts                  
npm notice === Tarball Details === 
npm notice name:          homebridge-garagedoor-ryobi             
npm notice version:       0.3.2                                   
npm notice package size:  23.5 kB                                 
npm notice unpacked size: 94.5 kB                                 
npm notice shasum:        5ca6bcf509b537b7931a4e3b18f093ffb792ad3d
npm notice integrity:     sha512-YJVtTVOgPlxiZ[...]cKcxVc7raD4sQ==
npm notice total files:   52                                      
npm notice 
+ homebridge-garagedoor-ryobi@0.3.2
-----------------------------------------------------------------
Hi knuckleheadsmiff!

A new version of the package homebridge-garagedoor-ryobi (0.3.2) was published at 2021-04-23T17:23:02.040Z from
75.4.201.162. The shasum of this package was 5ca6bcf509b537b7931a4e3b18f093ffb792ad3d.

If you have questions or security concerns, you can reply to this message or
email support@npmjs.com.

npm loves you.

**Comment by knuckleheadsmiff** [comment]
I invited you into the npmjs new organization "knuckleheadsmiff" associated with tis package to allow you to self publish. 

I hope I did it right. I don't know how to change the org name to something more useful. (I did not want to migrate everything to a new structure which npmjs kinda was wanting me to do; it was easier to just convert my account to an organization.)

**Pull request merged**
