### PR TITLE
Support finding the id from the name, and more

### PR DESCRIPTION
**Pull request by andyedinborough**
This adds support for:
1. Finding the id from the name of the door
2. Accessing the api endpoints without email and password in the query string
3. Other GDO models by dynamically looking up the port and module id's

### CODE REVIEW

**Comment by knuckleheadsmiff** [comment]
Hey thanks!

**Comment by knuckleheadsmiff** [comment]
So I’m actually new to all this...but I “auto merged” in your pull request but it did not all take? Am not sure the bast way to proceed to make sure all your changes are picked up. For example I don’t see the password changes merged in. I’m going to revert the merge and the. See if we can try again.

**Comment by knuckleheadsmiff** [comment]
I will look how to remerge this later today. Sorry. These tools are not intuitive.

**Comment by andyedinborough** [comment]
Odd... it looked like the merge commit #c64a20c had everything. Did you pull your master branch after the merge?

**Comment by andyedinborough** [comment]
This is what the history looks like to me: 
image

**Comment by knuckleheadsmiff** [comment]
Hummm... well that does look correct. I was just reviewing the files that was showing else where and I swear all the changes were not showing. I'' just try again. Clearly it is my user error. I am just not familiar enough with GitHub.

**Comment by knuckleheadsmiff** [comment]
OK, I reverted my revert. ;-) Seems OK now. I'm not sure what was going own.

**Comment by knuckleheadsmiff** [comment]
Can you look at https://github.com/knuckleheadsmiff/homebridge-garagedoor-ryobi/issues/7

The code should be working that you did as far as I can tell because the form parameters should be properly encoded by the request POST call.

Thanks

**Comment by knuckleheadsmiff** [comment]
Hi Andy. 

Your changes are causing problems with people who run multiple instances where they need to control multiple garage doors which require two different logins. Can you please look into this to see how you can fix this using cookies? Otherwise I am going to need to back out this change.

Here is the issue report: https://github.com/knuckleheadsmiff/homebridge-garagedoor-ryobi/issues/10#

Thanks.

**Comment by knuckleheadsmiff** [comment]
Note to self: If we revert the change and blackout the code using cookies I will need to fix this bug: #7 where the par word was not being properly encoded.

https://github.com/knuckleheadsmiff/homebridge-garagedoor-ryobi/issues/7

**Comment by andyedinborough** [comment]
I'll take a look

**Pull request merged**
